apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcm-backend
  template:
    metadata:
      labels:
        app: hcm-backend
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
      - name: backend
        image: ghcr.io/panikaa/hcm-backend:bc0f1f36d4759ade29338561bbe2a292742b7944
        command: ["sh", "-c", "npx prisma migrate deploy && npm start"]
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: hcm-db
                key: DATABASE_URL
                
          - name: APP_ENV
            valueFrom:
              configMapKeyRef:
                name: hcm-config
                key: APP_ENV

          - name: WORKER_INTERVAL_SECONDS
            valueFrom:
              configMapKeyRef:
                name: hcm-config
                key: WORKER_INTERVAL_SECONDS
