apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcm-frontend
  template:
    metadata:
      labels:
        app: hcm-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: frontend
          image: ghcr.io/panikaa/hcm-frontend:cf5e4697d154e670fe7a4b1f6f3d7c50ca673aba
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: hcm-config
                  key: API_URL

