apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcm-frontend
  template:
    metadata:
      labels:
        app: hcm-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: frontend
          image: ghcr.io/panikaa/hcm-frontend:c0a5f07dcb6bb3c8787a5eab9c4c8ab09d90d388
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: hcm-config
                  key: API_URL

