apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcm-frontend
  template:
    metadata:
      labels:
        app: hcm-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/panikaa/hcm-frontend:d0dc1e4ea04821efb4b794054030fcf429c04f0d
          ports:
            - containerPort: 80
