resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - configmap.yaml
  - externalsecret-db.yaml
  - ingress.yaml
  - hpa-backend.yaml
  - clustersecretstore.yaml